// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package memberlistgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransportClient is the client API for Transport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransportClient interface {
	SendPacket(ctx context.Context, in *Message, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StreamPackets(ctx context.Context, opts ...grpc.CallOption) (Transport_StreamPacketsClient, error)
}

type transportClient struct {
	cc grpc.ClientConnInterface
}

func NewTransportClient(cc grpc.ClientConnInterface) TransportClient {
	return &transportClient{cc}
}

func (c *transportClient) SendPacket(ctx context.Context, in *Message, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/memberlistgrpc.ckit.rfratto.v1.Transport/SendPacket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transportClient) StreamPackets(ctx context.Context, opts ...grpc.CallOption) (Transport_StreamPacketsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Transport_ServiceDesc.Streams[0], "/memberlistgrpc.ckit.rfratto.v1.Transport/StreamPackets", opts...)
	if err != nil {
		return nil, err
	}
	x := &transportStreamPacketsClient{stream}
	return x, nil
}

type Transport_StreamPacketsClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type transportStreamPacketsClient struct {
	grpc.ClientStream
}

func (x *transportStreamPacketsClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *transportStreamPacketsClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TransportServer is the server API for Transport service.
// All implementations must embed UnimplementedTransportServer
// for forward compatibility
type TransportServer interface {
	SendPacket(context.Context, *Message) (*emptypb.Empty, error)
	StreamPackets(Transport_StreamPacketsServer) error
	mustEmbedUnimplementedTransportServer()
}

// UnimplementedTransportServer must be embedded to have forward compatible implementations.
type UnimplementedTransportServer struct {
}

func (UnimplementedTransportServer) SendPacket(context.Context, *Message) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPacket not implemented")
}
func (UnimplementedTransportServer) StreamPackets(Transport_StreamPacketsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamPackets not implemented")
}
func (UnimplementedTransportServer) mustEmbedUnimplementedTransportServer() {}

// UnsafeTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransportServer will
// result in compilation errors.
type UnsafeTransportServer interface {
	mustEmbedUnimplementedTransportServer()
}

func RegisterTransportServer(s grpc.ServiceRegistrar, srv TransportServer) {
	s.RegisterService(&Transport_ServiceDesc, srv)
}

func _Transport_SendPacket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransportServer).SendPacket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memberlistgrpc.ckit.rfratto.v1.Transport/SendPacket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransportServer).SendPacket(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transport_StreamPackets_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TransportServer).StreamPackets(&transportStreamPacketsServer{stream})
}

type Transport_StreamPacketsServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type transportStreamPacketsServer struct {
	grpc.ServerStream
}

func (x *transportStreamPacketsServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *transportStreamPacketsServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Transport_ServiceDesc is the grpc.ServiceDesc for Transport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Transport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "memberlistgrpc.ckit.rfratto.v1.Transport",
	HandlerType: (*TransportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPacket",
			Handler:    _Transport_SendPacket_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPackets",
			Handler:       _Transport_StreamPackets_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "memberlistgrpc.proto",
}
